name: Gh-Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Decode base64 secrests
        run: echo $CONFIG_KEYS | base64 --decode > lin/.configkeys.dart
        env:
          CONFIG_KEYS: ${{ secrets.CONFIG_KEYS }}
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /shanmukha_portfolio/
